In [29]:
import torch
import numpy as np

In [19]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [26]:
x1 = x.reshape((3,4))
x1

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
data_2d = [[2,1,4,3],[1,2,3,4],[4,3,2,1]]
torch.tensor(data_2d)

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [13]:
data_3d = [[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]
torch.tensor(data_3d).shape

torch.Size([1, 3, 4])

In [14]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

我们也可以把多个张量连结在一起

In [27]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.zeros((3,4))
torch.cat((X,Y), dim=0), torch.cat((X,Y),dim=1) # dim=0是最外面的括号，1是第二个，2是第三个，以此类推

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]),
 tensor([[ 0.,  1.,  2.,  3.,  0.,  0.,  0.,  0.],
         [ 4.,  5.,  6.,  7.,  0.,  0.,  0.,  0.],
         [ 8.,  9., 10., 11.,  0.,  0.,  0.,  0.]]))

In [31]:
X_array = X.numpy()
X_tensor = torch.tensor(X_array)
type(X_array), type(X_tensor)

(numpy.ndarray, torch.Tensor)

In [32]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)